name: Tests cases

# Build on every branch push, tag push, and pull request change:
on: [push, pull_request]

jobs:
  check_if_output_files_changed:
    name: Check if output files changed
    runs-on: ubuntu-latest

    steps:
      - name: Checkout reposistory
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup requirements
        run: |
          python3 -m pip install -U -r requirements.txt
          python3 -m pip install -U maturin

      - name: Install local mapfile_parser
        run: python3 -m pip install .

      - name: Update tests outputs
        run: python3 tests/update_outputs.py

      - name: Check if there are any changes in the test cases
        id: tests_changes
        uses: tj-actions/verify-changed-files@v14

      - name: Check there are no changes in the outputs
        if: steps.tests_changes.outputs.files_changed == 'true'
        run: |
          echo "Changed files: ${{ steps.tests_changes.outputs.changed_files }}"
          echo "Please install the latest changes, run \`python3 tests/update_outputs.py\`, check the changes are desirable and commit the result"
          exit 1

  check_progress_nonmatchings:
    name: Check progress by NON_MATCHING symbols
    runs-on: ubuntu-latest

    steps:
      - name: Checkout reposistory
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup requirements
        run: |
          python3 -m pip install -U -r requirements.txt
          python3 -m pip install -U maturin

      - name: Install local mapfile_parser
        run: python3 -m pip install .

      - name: Update tests outputs
        run: python3 tests/check_progress_nonmatchings.py

  check_frontends:
    name: Check frontends aren't broken
    runs-on: ubuntu-latest

    steps:
      - name: Checkout reposistory
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup requirements
        run: |
          python3 -m pip install -U -r requirements.txt
          python3 -m pip install -U maturin

      - name: Install local mapfile_parser
        run: python3 -m pip install .

      - name: bss_check
        run: python3 -m mapfile_parser bss_check tests/maps/drmario64.us.map tests/maps/drmario64.us.map

      - name: first_diff
        run: python3 -m mapfile_parser first_diff tests/maps/drmario64.us.map tests/maps/drmario64.us.map tests/maps/drmario64.us.map tests/maps/drmario64.us.map

      - name: jsonify
        run: python3 -m mapfile_parser jsonify tests/maps/drmario64.us.map

      - name: objdiff_report
        run: python3 -m mapfile_parser objdiff_report tests/maps/drmario64.us.map objdiff_report.json

      - name: pj64_syms
        run: python3 -m mapfile_parser pj64_syms tests/maps/drmario64.us.map

      - name: progress
        run: python3 -m mapfile_parser progress tests/maps/drmario64.us.map asm asm/nonmatchings

      - name: sym_info
        run: python3 -m mapfile_parser sym_info tests/maps/drmario64.us.map entrypoint

      - name: symbol_sizes_csv
        run: python3 -m mapfile_parser symbol_sizes_csv tests/maps/drmario64.us.map

      - name: upload_frogress
        run: python3 -m mapfile_parser upload_frogress tests/maps/drmario64.us.map asm asm/nonmatchings drmario64 us code --verbose --dry-run
